language: java
jdk: openjdk8

install: true

script: mvn -f steps/step-2/pom.xml clean compile

before_deploy: ./.run.jekyll.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  on:
    branch: master
